name: Sponsor Labeler
author: Daniel Cazzulino
description: |
    A GitHub Action that labels issues and pull requests if 
    the creator is a sponsor (directly or indirectly via org or contributions).

inputs:
  label: 
    description: The default sponsor label to apply to the issue or pull request. Defaults to "sponsor ðŸ’œ".
    required: false
    default: 'sponsor ðŸ’œ'
  contrib-label: 
    description: The label to apply to the issue or pull request for past contributors. Defaults to "sponsor ðŸ’š".
    required: false
    default: 'sponsor ðŸ’š'
  silver-label: 
    description: The label to apply when sponsor amount is above the silver-amount. Defaults to "sponsor ðŸ¤".
    required: false
    default: 'sponsor ðŸ¤'
  silver-amount:
    description: Sponsors over this amount are labeled with silver-label instead. Defaults to 50.
    required: false
    default: 50
  gold-label: 
    description: The label to apply when sponsor amount is above the gold-amount. Defaults to "sponsor ðŸ’›".
    required: false
    default: 'sponsor ðŸ’›'
  gold-amount:
    description: Sponsors over this amount are labeled with gold-label instead. Defaults to 100.
    required: false
    default: 100
  sponsorable: 
    description: The account to check for sponsorship. Defaults to the repository owner.
    required: false
    default: ${{ github.repository_owner }}
  token:
    description: The token to use for querying the GitHub API for sponsorship information. Typically set to secrets.GH_TOKEN.
    required: true
  verbose:
    description: Whether to perform verbose logging when failing to find a sponsorship. Defaults to false.
    required: false
    default: false

branding:
  icon: heart
  color: purple

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: ðŸ’œ sponsor
      if: ${{ !endsWith(github.event.sender.login, '[bot]') && github.event.sender.login != inputs.sponsorable }}
      shell: pwsh
      env: 
        SPONSORABLE: ${{ inputs.sponsorable }}
        SPONSOR_LABEL: ${{ inputs.label }}
        SPONSOR_CONTRIB_LABEL: ${{ inputs.contrib-label }}
        SPONSOR_SILVER_LABEL: ${{ inputs.silver-label }}
        SPONSOR_SILVER_AMOUNT: ${{ inputs.silver-amount }}
        SPONSOR_GOLD_LABEL: ${{ inputs.gold-label }}
        SPONSOR_GOLD_AMOUNT: ${{ inputs.gold-amount }}
        SPONSOR_SENDER_LOGIN: ${{ github.event.sender.login }}
        SPONSOR_SENDER_ID: ${{ github.event.sender.node_id }}
        SPONSOR_ISSUE: ${{ github.event.issue.number || github.event.pull_request.number }}
        SPONSOR_VERBOSE: ${{ inputs.verbose }}
        GH_TOKEN: ${{ inputs.token }}
      run: sponsor-labeler.ps1
